### ISSUE TITLE
keymap for vim or emacs similar with codemirror keymap

### ISSUE THREAD

**Issue by ZhuZhengyi** [marktext/muya#10]
codemirror keymap: https://github.com/codemirror/CodeMirror/tree/master/keymap

monaco-vim: implement a monaco-vim codemirror adaptor for monaco-editor with vim keymap:
https://github.com/brijeshb42/monaco-vim

**Comment by fxha** [comment]
Duplicate of https://github.com/marktext/marktext/issues/596 and https://github.com/marktext/marktext/issues/1292. Closing this issue because Muya is currently developed in Mark Text repository.
