### ISSUE TITLE
When using the shortcut key, the style of the previous line will be lost

### ISSUE THREAD

**Issue by ch3n90** [marktext/muya#109]
When using the shortcut key to bold the text, after entering a newline, the bold style of the previous line will be lost

![screengif](https://github.com/marktext/muya/assets/20728437/1b0c9785-b331-4782-9b0f-fc04b17b2478)

**Comment by Jocs** [comment]
What's the shortcut key? `Cmd + B` ?

**Comment by ch3n90** [comment]
> What's the shortcut key? `Cmd + B` ?

yeap, ctrl + b on win32

**Comment by Jocs** [comment]
It may not support the win system yet, I just tested it on the macOS system. Now the keybinds are all under the UI formatPicker folder, PR welcomed.
