### ISSUE TITLE
Using Muya with react throws error

### ISSUE THREAD

**Issue by UmangThapliyal** [marktext/muya#12]
Hello, Loved marktext and wanted to use Muya in my current project for markdown support.
Currently my project is a simple create-react-app where I am trying to use muya I went through the doc and getting the below error can someone help me

![image](https://user-images.githubusercontent.com/34316267/75998082-43da5700-5f26-11ea-97b5-95bea8c0cc4f.png)

I have already installed it so not sure what is the issue

BTW love MarkText and muya will be a killer if I can contribute in some way please let me know I will be happy to contribute maybe some small issue

**Comment by Jocs** [comment]
This repository is used to refactor muya alone, and can be used for browser applications. The npm package has not been released yet,If you want to experience it, we can publish a trial version.
