### ISSUE TITLE
Muya & nodejs

### ISSUE THREAD

**Issue by FilipVerhaeghe** [marktext/muya#13]
The readme.md says that Muya is not ready for production status, but at the same time MarkText is using it, and it seems quite stable, but that is using ES6. Is Muya still dependent on Electron today?

Second, in MarkText, Muya is in a subdirectory. However, it is using resources that are in the `node_modules`. The document says "Muya is available as a stand-alone library" but am I right to interpret this as a "stand-alone library that uses nodejs"? I am asking because I am looking to isolate Muya from MarkText, and am trying to understand its dependencies.

Thanks.

**Comment by Jocs** [comment]
>The readme.md says that Muya is not ready for production status, but at the same time MarkText is using it, and it seems quite stable, but that is using ES6. Is Muya still dependent on Electron today?
