### ISSUE TITLE
Code Block Issue

### ISSUE THREAD

**Issue by ejabu** [marktext/muya#14]
### Problem : 
I always get this error message

![image](https://user-images.githubusercontent.com/2019630/79686099-0167a200-8268-11ea-97b2-13f779c963d2.png)

## when I paste a code blocks like this 

![2020-04-19_18-30-30](https://user-images.githubusercontent.com/2019630/79686711-9a002100-826c-11ea-9baa-4d8339b4858e.gif)

## It seems from this line

src\muya\lib\selection\index.js : 344
```
  select (startNode, startOffset, endNode, endOffset) {
    const range = this.doc.createRange() 
    range.setStart(startNode, startOffset) <-- This Line
    if (endNode) {
      range.setEnd(endNode, endOffset)
    } else {
      range.collapse(true)
    }
    this.selectRange(range)
    return range
  }
```

**Comment by Jocs** [comment]
please try the latest commit.
