### ISSUE TITLE
Functions are undefined

### ISSUE THREAD

**Issue by neopostmodern** [marktext/muya#145]
- [x] Searched existing issues to avoid creating duplicates.
- [x] Confirmed that it can be reproduced in muya.

----

**Describe the bug**
All of the functions on an instantiated Muya are undefined. Below is just one example, I inspected the object and *all* functions are `undefined`.

**To Reproduce**
```ts
import Muya from '@marktext/muya';
import { useEffect, useRef } from 'react';

const RichMarkdownEditor = ({
  markdown,
  onBlur,
}: {
  markdown: string;
  onBlur: (value: string) => void;
}) => {
  const muyaContainer = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!muyaContainer.current) {
      return;
    }

    const muya = new Muya(muyaContainer.current);
    muya.setContent(markdown);
  }, [muyaContainer]);

  return <div ref={muyaContainer}>Muya editor loading...</div>;
};

export default RichMarkdownEditor;
```
Upon execution you immediately get "TypeError: muya.setContent is not a function"

**Expected behavior**
Use the functions.

**Actual behavior**
Error is thrown.

**Operation System and Browser version (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox 119 (x86)

**Muya Version**
0.2.5

**Comment by Jocs** [comment]
```ts
const options: any = {
      disableHtml: true,
};

if (jsonState.length) {
    options.json = jsonState;
} else {
    options.markdown = markdown;
}
const muya = new Muya(editorRef.current, options);

muya.init();
```

you can put your markdown in the options, and call `muya.init`

There is an example in the example folder.

**Comment by yfwz100** [comment]
Why not call `init` inside constructor instead of calling `init()` explicitly?
