### ISSUE TITLE
Please publish the documents

### ISSUE THREAD

**Issue by Aini2016** [marktext/muya#147]
A great markdown editor! Please publish the documents.

**Comment by Aini2016** [comment]
Will the project be continuously optimized

**Comment by Jocs** [comment]
@Aini2016 This project will continue to be developed, and it is currently available, and it will be refactored again this year, providing plug-in capabilities, lifecycle capabilities, etc. and reducing the cost of UI plug-in development, and then releasing documentation

**Comment by Aini2016** [comment]
that's great！！！
