### ISSUE TITLE
[Feature] Sample code required

### ISSUE THREAD

**Issue by hyfree** [marktext/muya#156]
我按照文档和示例代码写了一个最小示例，但是他无法运行。

I wrote a minimal code example following the documentation and sample code, but it doesn't work.

https://github.com/hyfree/MuyaExample

如果有人可以提供帮助，我将非常感谢。
If anyone can help, I would greatly appreciate it.

感谢
thanks！

**Comment by hyfree** [comment]
已经解决

**Comment by hyfree** [comment]
我感觉是是丢失了CSS和图标资源的引用

**Comment by Jocs** [comment]
我试了下你的仓库，可以运行了？

**Comment by hyfree** [comment]
https://github.com/marktext/muya/pull/157

引入css后解决
