### ISSUE TITLE
Undo throw an error when markdown content only have sharp

### ISSUE THREAD

**Issue by kamesan012** [marktext/muya#171]
- [x] Searched existing issues to avoid creating duplicates.

- [x] Confirmed that it can be reproduced in muya.

----

**Describe the bug**
Undo throw an error when markdown content only have sharp.

**To Reproduce**
1. input `# ` in the editor
2. call undo function
3. See error in devtools

**Expected behavior**
Don't throw any errors and undo it correctly.

**Actual behavior**
Throw an error.

**Operation System and Browser version (please complete the following information):**
 - OS: [win11]
 - Browser: [Chrome 128.0.6613.113 (arm64)]

**Muya Version**
v0.0.32

**Screenshots / Screencasts（Optional）**
![image](https://github.com/user-attachments/assets/473cf340-a6df-472a-bfa5-6b05d688a9e4)

**Comment by sunshineshenjin** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
