### ISSUE TITLE
NPM Package Support

### ISSUE THREAD

**Issue by TankNee** [marktext/muya#29]
I'm going to use muya in my Electron application, but the muya package that published on npm has not updated until last year, so I have to copy the muya folder from marktext project. I reckon that is so sophisticated to use muya.
This is the application that use muya as preview editor [Memocast](https://github.com/TankNee/Memocast/tree/rebuild/analysis)

**Comment by Jocs** [comment]
@TankNee The muya in the marktext repository is the previous version. This repository is used to refactor muya. It is currently 80% complete, so it has not been published to npm. If you want to try it out, I can publish a preemptive version on npm , But not recommended for production usage.

**Comment by TankNee** [comment]
> @TankNee The muya in the marktext repository is the previous version. This repository is used to refactor muya. It is currently 80% complete, so it has not been published to npm. If you want to try it out, I can publish a preemptive version on npm , But not recommended for production usage.

thanks, I have migrated muya from marktext repo that is excellent.
