### ISSUE TITLE
Using Muya without Vue/ES6

### ISSUE THREAD

**Issue by BrianHung** [marktext/muya#3]
Hi, I’m wondering how to use the Muya library from the Marktext repository only using JavaScript, and not Vue & ES6. The main reasons being I’m relatively new to JS and the app I’m trying to build is pretty simple. 

I’ve tried following the Muya example included in Jocs’s GitHub repository and looked at files given in this repository, but got stuck importing modules like TablePicker such as here,

```bash
Muya.use(TablePicker)
```
since it seems `import TablePicker` is specific to Vue/ES6, and does not work as a module in Chrome. This issue also occurs in each modules’ index.js files since the import statements also follow that formatting.

I’ve tried building the index.min.js from scratch using the web pack config; and as a result get that file along with a bunch of x.index.js files — this seems similar to the chunks in the Muya example?

If this is not an appropriate topic, I apologize and will try to seek help elsewhere.

**Comment by Jocs** [comment]
> I’m relatively new to JS and the app I’m trying to build is pretty simple.

Because muya is still under development, so you can only use the source code in `Mark Text` library, like the `Muya example`. So you need to use ES6. But Vue is not necessary, you can also use other framework like React \ Angular.

Maybe you need to use babel and webpack to transform ES6 to ES5 in your web application if you want it run in old browsers.

**Comment by BrianHung** [comment]
Ok, I think I figured it out. 😄 

For anyone new like me, you need a bundler such as **webpack** to _transpile_ the Muya source code written in Typescript to ES6 (?) to something compatible and usable by Chrome – this is done through **babel** [1]. This is mainly because of the import statements. Webpack also helps to create an `index.min.js` & `css`, along with various chunks that can be loaded later.

Currently, my `webpack.config.js`looks like

```javascript
'use strict'

require("@babel/polyfill");

const path = require('path')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const postcssPresetEnv = require('postcss-preset-env')
const UglifyJsPlugin = require('uglifyjs-webpack-plugin')

module.exports = {
  mode: 'development',
  devtool: '',
  entry: ['@babel/polyfill', './editor.js'],
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          { loader: 'css-loader', options: { importLoader: 1 } },
          {
            loader: 'postcss-loader',
            options: {
              ident: 'postcss',
              plugins: () => [
                postcssPresetEnv({
                  stage: 0
                })
              ]
            }
          }
        ]
      },
      {
        test: /\.js$/,
        use: {
            loader: 'babel-loader',
            options: {
              presets: [
                '@babel/preset-env',
                {
                plugins: [
                  '@babel/plugin-proposal-class-properties', '@babel/plugin-syntax-dynamic-import'
                ]
                }
              ]
            }
          },
        exclude: /node_modules/,
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        use: {
          loader: 'url-loader',
          query: {
            limit: 10000,
            // name: 'imgs/[name]--[folder].[ext]'
          }
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: 'media/[name]--[folder].[ext]'
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        use: {
          loader: 'url-loader',
          query: {
            limit: 10000,
            name: 'fonts/[name]--[folder].[ext]'
          }
        }
      }
    ]
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: 'index.min.css'
    })
  ],
  output: {
    filename: 'index.min.js',
    libraryTarget: 'umd',
    library: 'Muya',
    path: path.join(__dirname, './dist'),
    publicPath: "/dist/"
  },
  resolve: {
    extensions: ['.js', '.json', '.css', '.node']
  },
  node: {
    fs: "empty"
  },
  optimization: {
  minimizer: [
    new UglifyJsPlugin({
      uglifyOptions: {
        output: {
          comments: false
        }
      }
    })
  ]
  }
}
```

And then made the following`.js` file as an entry point, including all the modules within `/lib/ui/` to make sure they were included within the `index.min.js`. Got that through [the original Muya example](https://github.com/Jocs/muya-example/blob/master/src/App.vue), but I'm not using Vue.

```javascript
import Muya from './lib'
import TablePicker     from './lib/ui/tablePicker'
import QuickInsert     from './lib/ui/quickInsert'
import CodePicker      from './lib/ui/codePicker'
import EmojiPicker     from './lib/ui/emojiPicker'
import ImagePathPicker from './lib/ui/imagePicker'
import FormatPicker    from './lib/ui/formatPicker'
import './themes/light.css'

Muya.use(TablePicker)
Muya.use(QuickInsert)
Muya.use(CodePicker)
Muya.use(EmojiPicker)
Muya.use(ImagePathPicker)
Muya.use(FormatPicker)

export default Muya
```

Also needed to install all the npm dependencies.

[1] Mostly read through [this](https://medium.freecodecamp.org/javascript-modules-part-2-module-bundling-5020383cf306).
