### ISSUE TITLE
Code block language is updated when the user types

### ISSUE THREAD

**Issue by fxha** [marktext/muya#53]
The code block language is updated when the user types, which result in multiple null pointer exception and type errors.

**Comment by Jocs** [comment]
>The code block language is updated when the user types, which result in multiple null pointer exception and type errors.

How to reproduce this issue?

**Comment by fxha** [comment]
Just type an empty language identifier or garbage text. You also can't unset an identifier and `jsasjdaskjd` is interpreted as `js`.

https://user-images.githubusercontent.com/22716132/152682463-aa85771b-c97d-4610-9704-5428b8054571.mp4
