### ISSUE TITLE
Editor uses a very large horizontal space

### ISSUE THREAD

**Issue by fxha** [marktext/muya#58]
The editor area behaves different on Chrome and Firefox. Chrome has no additional horizontal space but Firefox use a scrollbar and jumps e.g. on `/` input to the right that the editor is not in view-port.

**Comment by Jocs** [comment]
This should be a compatibility issue. I didn't test it on browsers other than Chrome when I developed it, because the original idea was to replace muya in marktext. Electron uses the Chrome kernel. Of course, it still needs to be used on multiple browsers in the future. Tested and developed.
