### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by ninest** [marktext/muya#6]
I would like to use it in a project. I just wanted to know if it's still being updated.

**Comment by Jocs** [comment]
muya(version < 1.0.0) is still under development in [marktext](https://github.com/marktext/marktext) project. you can use muya by copy muya folder in marktext project to you project.

**Comment by berserkwarwolf** [comment]
Hi @Jocs , so have you agreed to make a web version of MarkText  ?

**Comment by Jocs** [comment]
This repository is used to refactor muya alone, and can be used for browser applications. The npm package has not been released yet
