### ISSUE TITLE
Muya dosen't work in Safari?

### ISSUE THREAD

**Issue by alants56** [marktext/muya#64]
Muya doesn't work in Safari:

 SyntaxError: Invalid regular expression: invalid group specifier name

![image](https://user-images.githubusercontent.com/10046245/155256884-0e5ec890-b0e6-46a0-902a-d6fefe4dddf6.png)

It seem that Safari doesn't support lookbehind yet.

https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

**Comment by Jocs** [comment]
I dev and test muya on Chrome, and have not test it on Safari.

**Comment by True-cc** [comment]
It doesn't work on Gnome Web (formerly Epiphany) either (which also uses WebKit)
![image](https://user-images.githubusercontent.com/38010540/169440286-ee9cafb4-8034-4037-a368-8ac0bcf80091.png)

I also tested it on Falkon and Konqueror and they both work.

Here are some specs from https://www.whatismybrowser.com/ of, from left to right, Konqueror, Gnome web, and Falkon :
![image](https://user-images.githubusercontent.com/38010540/169442037-4dd184fd-1857-4e56-b404-ce5beeab4f50.png)
(I have 32GB of ram btw, not 8 :)

Webkit browsers hurt my brainnnnnn

**Comment by Jocs** [comment]
Safari should now support regular group names? Other issues are welcome
