### ISSUE TITLE
The requested module '/node_modules/.vite/deps/dompurify.js?v=3e090982' does not provide an export named 'isValidAttribute'

### ISSUE THREAD

**Issue by impohcom** [marktext/muya#70]
muya\lib\utils\dompurify.js     Incompatible vite

```js
import DOMPurify from 'dompurify'
const isValidAttribute = DOMPurify.isValidAttribute
const sanitize = DOMPurify.sanitize

export {
  isValidAttribute
}

export default sanitize
```

**Comment by IronCode1024** [comment]
I have the same problem,Also used vite.

**Comment by gitcetop** [comment]
> I have the same problem,Also used vite.

To use the  https://github.com/marktext/marktext   Modified into vue
I am now directly using MarkText to modify it to vue2
There are too many problems with this version

**Comment by Jocs** [comment]
Now the project is not work with built, so vite may not be supported，PR is welcomed

**Comment by Jocs** [comment]
The project has already provided a built version. You can try installing the latest version.
