### ISSUE TITLE
Forked codebases between this repo and marktext

### ISSUE THREAD

**Issue by themightychris** [marktext/muya#78]
Looking to potentially adopt this as a dependency, it's a bit concerning that there seem to be two parallel copies of muya right now, here and within the marktext repository.

Are there plans to eventually switch Marktext to relying on releases from this repository, or are there hard reasons they need to stay forks?

What does development on muya look like? Does it mostly happen first in Marktext and then improvements/fixes get backported to Muya as needed? It looks like that from Muya's history, but I'm wondering if there's any regularized process yet for if/when changes to marktext/muya get ported to muya

This might be good stuff to elaborate on in [Muya's FAQ](https://github.com/marktext/muya#faq)

**Comment by Jocs** [comment]
The muya in this repo will eventually replace the version in marktext
