### ISSUE TITLE
Multiple instances of Muya.

### ISSUE THREAD

**Issue by uvisgrinfelds** [marktext/muya#9]
Love the Muya so far! 

I want to be able to have multiple instances of the editor on a single page. Will this be possible in the future? Any ideas how would I go about it? 

Thanks!

**Comment by Jocs** [comment]
>I want to be able to have multiple instances of the editor on a single page. Will this be possible in the future? Any ideas how would I go about it?

It's seems impossible now, Because the editor only has a unique id, which is not currently considered for multiple editor instances on a page, why don't you share an editor instance?

**Comment by Jocs** [comment]
I'm sorry to reply to you today, mainly because I've been busy recently
